 - name: installing postgresql using shell
    shell: "dnf install -y postgresql-server postgresql-contrib python3-psycopg2"

    # - name: Create Cluster
    #   ansible.builtin.command:
    #     cmd: postgresql-setup --initdb
    #   args:  
    #     creates: /var/lib/pgsql/data/PG_version

    # - name: start and enable postgresql
    #   ansible.builtin.systemd:
    #     name: postgresql
    #     state: started
    #     enabled: true 