---
- name: Ensure firewalld is installed and enabled
  dnf:
    name: firewalld
    state: present

- name: Start and enable firewalld
  service:
    name: firewalld
    state: started
    enabled: yes

- name: Allow SSH service in firewalld
  firewalld:
    service: ssh
    permanent: yes
    state: enabled
    immediate: yes