---
- name: Install Java (OpenJDK 8)
  ansible.builtin.package:
    name: "{{ 'java-1.8.0-openjdk' if ansible_os_family == 'RedHat' else 'openjdk-8-jdk' }}"
    state: present

- name: Create Solr user
  ansible.builtin.user:
    name: "{{ solr_user }}"
    shell: /bin/bash
    home: "{{ solr_install_dir }}"
    create_home: yes

- name: Download Solr archive
  ansible.builtin.get_url:
    url: "https://archive.apache.org/dist/lucene/solr/{{ solr_version }}/solr-{{ solr_version }}.tgz"
    dest: "/tmp/solr-{{ solr_version }}.tgz"
    mode: '0644'
    timeout: 60

- name: Extract Solr installer
  ansible.builtin.unarchive:
    src: "/tmp/solr-{{ solr_version }}.tgz"
    dest: /tmp
    remote_src: yes

- name: Run Solr install script
  ansible.builtin.command: "bash /tmp/solr-{{ solr_version }}/bin/install_solr_service.sh /tmp/solr-{{ solr_version }}.tgz"
  args:
    creates: /etc/init.d/solr
  register: install_output

- name: Enable and start Solr
  ansible.builtin.systemd:
    name: solr
    state: started
    enabled: true
    daemon_reload: yes

- name: Open port 8983 in firewalld (optional)
  ansible.posix.firewalld:
    port: 8983/tcp
    permanent: true
    state: enabled
    immediate: true
  when: ansible_os_family == "RedHat"

- name: Check Solr service
  ansible.builtin.uri:
    url: "http://localhost:8983/solr/"
    return_content: yes
  register: solr_check
  failed_when: solr_check.status != 200

- name: Print success
  ansible.builtin.debug:
    msg: "Solr installed and running at http://{{ inventory_hostname }}:8983/solr/"