---
- name: Update dnf cache
  ansible.builtin.dnf:
    update_cache: yes
  become: true

- name: Install Java package
  ansible.builtin.dnf:
    name: java-1.8.0-openjdk-devel
    state: present
  
- name: Download Solr
  ansible.builtin.get_url:
    url: https://archive.apache.org/dist/lucene/solr/8.11.2/solr-8.11.2.tgz
    dest: /tmp/solr-8.11.2.tgz
    mode: '0644'

- name: Create Solr directory
  ansible.builtin.file:
    path: /opt/solr
    state: directory
    owner: solr
    group: solr
    mode: '0755'

- name: Extract Solr archive
  ansible.builtin.unarchive:
    src: /tmp/solr-8.11.2.tgz
    dest: /opt
    remote_src: yes
    owner: solr
    group: solr
    creates: /opt/solr/bin/solr

# - name: Symlink /opt/solr to extracted dir
#   ansible.builtin.file:
#     src: /opt/solr-8.11.2
#     dest: /opt/solr
#     state: link

- name: Copy solr service file
  ansible.builtin.copy:
    src: solr.service
    dest: /etc/systemd/system/solr.service
    owner: solr
    group: solr
    mode: '0644'

- name: Create Solr data directory
  ansible.builtin.file:
    path: /var/solr
    state: directory
    owner: solr
    group: solr
    mode: '0755'

- name: Start and enable Solr service
  ansible.builtin.systemd:
    name: solr
    state: started
    enabled: true
    daemon_reload: yes

- name: Open firewall port for Solr
  ansible.builtin.firewalld:
    port: 8983/tcp
    permanent: true
    state: enabled
    immediate: yes