---
- name : Base OS
  hosts: os_upgrade
  become: true
  roles:
    - { role: update_os, tags: ["os_update"]}
    
- name: Install MongoDB
  hosts: mongo
  become: true
  roles:
    - { role: setup_mongo, tags: ["mongo_setup"] }

- name: Setup LVM
  hosts: mongo
  become: true
  roles:
    - { role: setup_lvm, tags: ["lvm_setup"] }

- name: Install Solr
  hosts: solr
  become: true
  roles:
    - { role: install_packages, tags: install_solr }

- name: Mount Disks
  hosts: solr
  become: true
  vars:
    disk_device: /dev/sdb
    partition_device: /dev/sdb1
    mount_point: /mnt/data
  roles:
    - { role: add_generic_partition, tags: mount_disk }

- name: Install postgres
  hosts: postgres
  become: yes
  roles:
    - installing_postgres
  tags:
    - install 

- name: Create LVM partitions for postgres
  hosts: postgres
  become: yes
  roles:
    - LVM_partition_postgres
  tags:
    - partition
