---
- name: Install Solr
  hosts: web
  become: true
  vars:
    disk_device: /dev/sdb
    partition_device: /dev/sdb1
    mount_point: /mnt/data
  roles:
    - { role: install_packages, tags: solr }

- name: Mount Disks
  hosts: web
  become: true
  vars:
    disk_device: /dev/sdb
    partition_device: /dev/sdb1
    mount_point: /mnt/data
  roles:
    - { role: add_generic_partition, tags: solr }

- name: Install postgres
  hosts: all
  become: yes
  roles:
    - installing_postgres
  tags:
    - postgres 

- name: Create LVM partitions for postgres
  hosts: all
  become: yes
  roles:
    - LVM_partition_postgres
  tags:
    - postgres
