- name: Install postgres
  hosts: all
  become: yes
  roles:
    - installing_postgres
  tags:
    - install 

- name: Create LVM partitions for postgres
  hosts: all
  become: yes
  roles:
    - LVM_partition_postgres
  tags:
    - partition
