---
- name: Install Solr
  hosts: web
  become: true
  vars:
    solr_version: "8.11.2"
    solr_user: "solr"
    solr_install_dir: "/opt/solr"
    solr_service_file: "/etc/systemd/system/solr.service"
  roles:
    - { role: install_packages, tags: install_solr }

- name: Mount Disks
  hosts: web
  become: true
  vars:
    disk_device: /dev/sdb
    partition_device: /dev/sdb1
    mount_point: /mnt/data
  roles:
    - { role: add_generic_partition, tags: mount_disk }

- name: Install postgres
  hosts: all
  become: yes
  roles:
    - installing_postgres
  tags:
    - install 

- name: Create LVM partitions for postgres
  hosts: all
  become: yes
  roles:
    - LVM_partition_postgres
  tags:
    - partition
