---
- name: Install Solr and Mount Disks
  hosts: all
  become: true
  vars:
    disk_device: /dev/sdb
    partition_device: /dev/sdb1
    mount_point: /mnt/data
  roles:
    - { role: install_packages, tags: install_solr }

- name: Install Solr and Mount Disks
  hosts: all
  become: true
  vars:
    disk_device: /dev/sdb
    partition_device: /dev/sdb1
    mount_point: /mnt/data
  roles:
    - { role: add_generic_partition, tags: mount_disk }