---
- name : Base OS
  hosts: os_upgrade
  become: true
  roles:
    - { role: update_os, tags: ["os_update"]}

- name: Install MongoDB
  hosts: mongo
  become: true
  roles:
    - { role: setup_mongo, tags: ["mongo"] }

- name: Setup LVM
  hosts: mongo
  become: true
  roles:
    - { role: setup_lvm, tags: ["mongo"] }

- name: Install Solr
  hosts: solr
  become: true
  roles:
    - { role: install_packages, tags: solr }

- name: Mount Disks
  hosts: solr
  become: true
  vars:
    disk_device: /dev/sdb
    partition_device: /dev/sdb1
    mount_point: /mnt/data
  roles:
    - { role: add_generic_partition, tags: solr }

- name: Install postgres
  hosts: postgres
  become: yes
  roles:
    - {role: installing_postgres, tags: postgres}

- name: Create LVM partitions for postgres
  hosts: postgres
  become: yes
  roles:
    - {role: LVM_partition_postgres, tags: postgres}
  
