---
- name: Install MongoDB
  hosts: all
  become: true
  roles:
    - { role: setup_mongo, tags: ["mongo_setup"] }

- name: Setup LVM
  hosts: all
  become: true
  roles:
    - { role: setup_lvm, tags: ["lvm_setup"] }
