---
- name: Configure and install Solr
  hosts: install_solr
  become: true

  roles:
    - install_packages

- name: Mount disk
  hosts: mount_disk
  become: true
  vars:
    disk_device: /dev/sdb
    partition_device: /dev/sdb1
    mount_point: /mnt/data

  roles:
    - add_generic_partition

- name: Install Solr and Mount Disks
  hosts: solr
  become: true
  vars:
    disk_device: /dev/sdb
    partition_device: /dev/sdb1
    mount_point: /mnt/data
  roles:
    - install_packages
    - add_generic_partition